Merkulov Andrii HW_02_DJANGO(29) + HW_03_DJANGO(30-31)+login/registr
HECTPUMHUI/my_proj pull request #1
Opened 2023-02-07 22:27 UTC by HECTPUMHUI

2023-02-13 11:17 UTC, shorodilov requested changes
Це, начебто, повино працювати.
Але окремі частини зроблени дуже не охайно.
Доведи вже до розуму та "причепури" якось файно.
Важко сказати точно, бо тут намішано усього - але загалом складається враженя, що працюєш ти "без плану" і код гуляє із сторони в сторону.
Спочатку - розуміння того, що треба зробити і як саме це буде робитись, потім - написання коду.

2023-02-13 11:17 UTC, shorodilov commented on blogik/blogik/urls.py
> +from setuptools import namespaces
І навіщо це тут?

2023-02-13 11:17 UTC, shorodilov commented on blogik/blogik/settings.py
> +    'task',
кастомні застосунки зазвичай розміщують внизу.
загальний шаблон: "вбубовані застосунки - 3rd party - застосунки проекта"

2023-02-13 11:17 UTC, shorodilov commented on blogik/task/views.py
> +# class Blog(ListView):
Не лишай закоментований код

2023-02-13 11:17 UTC, shorodilov commented on blogik/task/views.py
> +        'cat_selected': 0,
Якщо бажаєш відстежувати обрану категорію, то ліпше контролювати це через `GET` параметри

2023-02-13 11:17 UTC, shorodilov commented on blogik/task/views.py
> +from django.views.generic import ListView, DetailView, CreateView
ти оці імпортував, але використовуєш лише 1 з 3.

2023-02-13 11:17 UTC, shorodilov commented on blogik/task/views.py
> +from django.contrib.auth.models import User
Якщо по-чесному, я не розумію навіщо тут половина імпорта.

2023-02-13 11:17 UTC, shorodilov commented on blogik/user/models.py
> +    is_admin = models.BooleanField('Is admin', default=False)
у базової моделі є поля `is_superuser` та `is_stuff`, що виконують схожу роль.
до того ж не зрозуміло, якщо якийсь запис користувача не адмін (`is_admin = False`) та не користувач (`is_user = False`), то хто він?

2023-02-14 19:08 UTC, HECTPUMHUI commented on blogik/blogik/urls.py
> +from setuptools import namespaces
це та подібні імпорти, що не застосовуються, а також код залишений закоментоваим, просто не охайність та "залишив на потім, ще на допрацювання")
виправлюсь, буду дотримуватися дзену)

2023-02-14 19:12 UTC, HECTPUMHUI commented on blogik/user/models.py
> +    is_admin = models.BooleanField('Is admin', default=False)
це я при створені в адмінці можу змінювати права вибираю чи адмін чи юзер і через цей парментр, відображав зареестрованим юзерам функціонал сайта))

2023-02-14 19:14 UTC, merged

2023-02-14 19:16 UTC, HECTPUMHUI reviewed
все виправив)